In [52]:
# Import Numpy library and assign a for an array
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [39]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)

# Vectorized Version
tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(c)
print("Vectorized Version:" + str(1000*(toc-tic))+" ms")

# Let's try non-vectorized version
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]* b[i]
toc = time.time()

print(c)
print("For Loop:"+str(1000*(toc-tic))+" ms")

250079.81427076398
Vectorized Version:6.948709487915039 ms
250079.81427076607
For Loop:723.1333255767822 ms


In [40]:
#u = np.exp(v)

#np.log(v)
#np.abs(v)
#np.maximum(v, 0)
#v**2
#1/v

In [41]:
#dZ = A - Y
#db = 1/m(np.sum(dZ))
#dw = 1/m*(X*dZ.T)

In [42]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [43]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [44]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [45]:
# Let's create a random numpy array
a = np.random.randn(5)

In [46]:
print(a)

[-0.19163668  0.47381501  0.53577665 -1.60230223 -0.29086079]


In [47]:
print(a.shape)
# this is called rank 1 array which is not recommended in any use in data analysis

(5,)


In [48]:
# Creating Random 5, 1 dimentional 5 row 1 column vector
a = np.random.randn(5,1)
b = np.random.randn(1,5) # This is 1,5 row vector

In [49]:
print(a)

[[-1.15473913]
 [ 0.01741048]
 [-0.52916638]
 [ 0.07336765]
 [ 0.28654692]]


In [50]:
print(a.T)
# This will give 1, 5 metrics

[[-1.15473913  0.01741048 -0.52916638  0.07336765  0.28654692]]


In [51]:
print(np.dot(a, a.T))

[[ 1.33342246e+00 -2.01045658e-02  6.11049121e-01 -8.47204934e-02
  -3.30886942e-01]
 [-2.01045658e-02  3.03124910e-04 -9.21304206e-03  1.27736616e-03
   4.98892023e-03]
 [ 6.11049121e-01 -9.21304206e-03  2.80017053e-01 -3.88236920e-02
  -1.51630995e-01]
 [-8.47204934e-02  1.27736616e-03 -3.88236920e-02  5.38281167e-03
   2.10232734e-02]
 [-3.30886942e-01  4.98892023e-03 -1.51630995e-01  2.10232734e-02
   8.21091378e-02]]


In [54]:
#assert(a.shape == (5, 1))

In [55]:
# a = a.reshape((5, 1)) # or
# a = a.reshape((1, 5))

In [60]:
a = np.random.randn(2,3)
print("shape of a is: " + str(a.shape))
b = np.random.randn(2,1)
print("shape of b is " + str(b.shape))
c = a+b
print(c.shape)

shape of a is: (2, 3)
shape of b is (2, 1)
(2, 3)


In [58]:
a = np.random.randn(12288,150)
b = np.random.randn(150,45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [65]:
a = np.random.randn(3,3)
b = np.random.randn(3,1)

c = a * b
print(c)
print(c.shape)

[[ 0.71392065 -0.3219712   0.82105961]
 [-0.72300329  0.26719483 -1.92266258]
 [ 1.97173315  1.36394652  1.85885365]]
(3, 3)


In [70]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)

c = a.T + b.T
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (1,4) 